name: Refresh Unrest Scores

on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-scores:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Generate scores
      run: |
        python calculate_unrest_score.py --hours 24
        python calculate_unrest_score.py --hours 48
        python calculate_unrest_score.py --hours 168

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and push new score files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin git@github.com:jeetb/civil-unrest-tracker.git
        git add data/final/unrest_scores_*.csv || echo "Nothing to add"
        git commit -m "Auto-update unrest scores" || echo "Nothing to commit"
        git push origin HEAD:main




